version: '3.8'

services:
  backend:
    build: .
    container_name: expense_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: expense_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis:latest
    container_name: expense-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
